configuration: Release
version: 1.0.0.{build}

before_build:
  - nuget restore

build:
  project: csharp-metar-decoder.sln
  verbosity: minimal

after_build:
  - ps: nuget pack csharp-metar-decoder\csharp-metar-decoder.nuspec -Version $env:APPVEYOR_BUILD_VERSION

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: CAjCS0NsYDheBeTgzVRW7JqNdHtHZrDo3y4oLBwCHv6IzTo/t5e7whWJrbt5Duf6

after_test:
  - nuget install NUnit.Runners -Version 3.8.0
  - nuget install OpenCover -Version 4.6.519
  - nuget install coveralls.net -Version 0.412
  - OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" -targetargs:"--result nunit2 csharp-metar-decoder-tests\bin\Release\csharp-metar-decoder-tests.dll" -returntargetcode:10000 -log:All -filter:"+[csharp-metar-decoder]* -[csharp-metar-decoder-tests*]*" -register:Path32 -output:".\cover_results.xml"
  - coveralls.net.0.412\tools\csmacnz.Coveralls.exe --opencover -i .\cover_results.xml

artifacts:
  - path: '**\csharp-metar-decoder.*.nupkg'

#deploy:
#  provider: NuGet
#  on:
#    branch: master
#  api_key:
#    secure: zgNT2DNyLuvf8sH+Y1kAI/aOL6E4S5zVHeadTWSFP1/vxVpEQ75QLxyBQMZr4A0n
#  skip_symbols: true
